title: Netflis - Platforma de Stream
description: Documentaci칩n de la plataforma de streaming con integraci칩n de MercadoPago
theme: jekyll-theme-cayman

# Configuraci칩n importante para Jekyll
defaults:
  -
    scope:
      path: "" # aplica a todos los archivos
    values:
      layout: default

# Especificar que los archivos .md deben ser procesados
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Configurar la p치gina principal
index_page: index.md 